title = "login toml config file"

[base]
    web_addr = ":9090"
    root_dir = "D:/workspace/community-cloud"
    var_dir = "D:/workspace/community-cloud"

[log_conf]
    project = "community"
    name = "main"
    log_dir  = "/log"
    log_level = "info"
    max_day = 7
    rotate_seconds = 3600
    extname=""

[database]
    [database.community-cloud]
        mysql_master_conf = "root:root@tcp(192.168.34.105:3306)/pscc?timeout=15s"
        mysql_slave_conf = "root:root@tcp(192.168.34.105:3306)/pscc?timeout=15s"
        enable = 1
    max_open_conn = 50
    max_idle_conn = 20
    max_life_time = 3600